### ISSUE TITLE
[feature request] Add total reload feature.

### ISSUE THREAD

**Issue by TobiasFeld22** [TobiasFeld22/Spark#10]
Instead of just reloading using "commands" or "functions"

Keeping it blank should reload everything.

<prefix> reload 
or 
<prefix> reload all
to reload all.

**Comment by sharletsings123** [comment]
<prefix>reload all looks better actually and gives an definition to the "reload everything"

**Comment by TobiasFeld22** [comment]
yeah, would probably be better.
I will start working on it, unless you want to

**Comment by sharletsings123** [comment]
I can't do much due to some reasons so I think you should take it up but I'll help in all ways I can as well as suggest if I have any ideas.

**Comment by TobiasFeld22** [comment]
ready to be tested in next Beta
