### ISSUE TITLE
[Feature request] native Event support

### ISSUE THREAD

**Issue by TobiasFeld22** [TobiasFeld22/Spark#11]
I would like to add native Event support,
you would have a folder like /functions or /commands, just with /events
Structure of an event file:

.name = String (Just for identification purposes when an error occurs. and to store it in the system)
.event = String (Is event name "ready" or "message", etc.)
.function = Function (function that happens when event is triggered)

**Comment by TobiasFeld22** [comment]
Started to work on changing internal coding to use events files instead of taking space in loading files.

**Comment by TobiasFeld22** [comment]
if nobody finds something bad i am going to put a new beta up.

**Comment by sharletsings123** [comment]
This would be a good idea as it seperates the events off the internals.

But wouldn't it be good to have a events, functions etc folders outside the commands folder and then load each of them up when the bot starts up by a small command in the internal?

**Comment by TobiasFeld22** [comment]
@sharletsings123 what do you mean?
it already loads in its own folder

**Comment by sharletsings123** [comment]
On this issue you said that there could be a folder inside the commands folder called functions etc, above I said that it would be good to have it outside the commands folder.

Anyways if it does then good.

**Comment by TobiasFeld22** [comment]
updated, i made a typo

**Comment by sharletsings123** [comment]
Ah kk

**Comment by sharletsings123** [comment]
Good that you updated it or else other would have been confused like me.
