### ISSUE TITLE
Commands - Subfolders

### ISSUE THREAD

**Issue by AJFire14** [TobiasFeld22/Spark#18]
Hello. Below is my suggestion of what could be added to Spark to improve organisation:

- Adding subfolders to commands. Basically, within the commands folder, the easy ability to create subfolders inside it to keep commands neatly in different sections for example:
> Bot
   > Commands
       > Moderation
       > Utility
       > Example 3 etc...

AJFire14#1004

**Comment by TobiasFeld22** [comment]
Moved to v0.0.7 rewrite due to needing complete new setup strategy, which would make this possible

**Comment by TobiasFeld22** [comment]
Added in v0.1
