### ISSUE TITLE
Channel type filtering

### ISSUE THREAD

**Issue by AJFire14** [TobiasFeld22/Spark#19]
Below is my suggestion:

Having the easy ability to set an option in each command where people can decide whether the command can be performed in DMs only, Guilds only OR Guilds & DMs. 

AJFire14#1004

**Comment by TobiasFeld22** [comment]
It "should" perform automatically inside dms, but a bug makes it error in the message handler,
 i will look into that.

I will also add the ability to filter out specific channels, something like:
`exports.ignoredchannels = ["dm", "group", "main"]`
Unless you have improvements to make on that.

**Comment by TobiasFeld22** [comment]
enhancement added, bug fixed 💪

**Comment by TobiasFeld22** [comment]
Did some bugfixing and is now fixed.
