### ISSUE TITLE
Improve ignoring bots behaviour

### ISSUE THREAD

**Issue by TobiasFeld22** [TobiasFeld22/Spark#20]
Currently if specified in the config that Spark should ignore bots, it will also ignore it in message functions, which could be problemetic for message scanning, autodelete in a channel, etc.

I want to change 
`allowBots: true`
to 
`allowBots: true` For ignoring message function and commands
`allowBots: "message"` For only ignoring commands.
`allowBots: "command"` For only ignoring messagefunctions

**Comment by TobiasFeld22** [comment]
From my quick testing i conclude that the issue has been resolved

**Comment by TobiasFeld22** [comment]
I kinda got this wrong, and while i can i want to redo it:

Instead of calling it "allowBots" i want to rename it to "ignoreBots", as that would make more sense.

**Comment by advaith1** [comment]
Usually, allowbots means to **not** ignore bots

**Comment by TobiasFeld22** [comment]
i know, that's what i am saying.

**Comment by sharletp** [comment]
Sounds good and makes more sence!
