### ISSUE TITLE
About command

### ISSUE THREAD

**Issue by AJFire14** [TobiasFeld22/Spark#35]
Includes a summary of Spark's aim & features. Include necessary links too.

**Comment by TobiasFeld22** [comment]
I would really like it if somebody can work on this at this moment, see the instructions in the command i have already added, the only thing that needs to change is the text inside it.

It should have some stats like server count, ram usage, owner of the bot application (can be found using `client.config.ownerID` and uptime.

Also it should show which version it's running (`spark.version`) and links to both the server and the website. https://discord.gg/TezD2Zg & https://discordspark.tk
