### ISSUE TITLE
Error in Code

### ISSUE THREAD

**Issue by RenderedPix** [TobiasFeld22/Spark#41]
Error located at [Picture](http://prntscr.com/il74p7)
Error: [Picture](http://prntscr.com/il74uc)
It seems to me this is a flaw in Spark's coding? 
`"AllowedImageSizes"`

**Comment by TobiasFeld22** [comment]
It's not a flaw in Spark's coding, but an error in Discord.js it seems.
It's recommended to use Discord.js 11.3 with Spark v0.0.6 or higher. From what i can see you're currently using discord.js master branch on github.

Here a link to the code:
https://github.com/discordjs/discord.js/blob/2a9fdef9e541e47196982055595e1987bc1de74e/src/util/Constants.js#L104
