### ISSUE TITLE
Reload: Edit "reloading" message instead of sending new "reloaded" message

### ISSUE THREAD

**Issue by advaith1** [TobiasFeld22/Spark#50]
For the `reload` command, Spark v0.0.x used to edit the "Reloading" message to "Successfully reloaded x commands". However. Spark v0.1 sends "Reloading all files..." then sends "Successfully reloaded all files." in a new message. 

It would be better if it edited the "Reloading" message instead of sending a new one.

**Comment by Sanil14** [comment]
Looks like this was not closed by the commit. Closing this now. 
Commit: eecb7a157d427f0e3d392bc4a1691cc9ab860c59
