### ISSUE TITLE
Get started link doesn't exist

### ISSUE THREAD

**Issue by PrinceAlii** [TobiasFeld22/Spark#53]
When you click the "Getting Started" link it brings you to a 404 not found page.
I think the correct link is: https://discordspark.com/getting-started

**Comment by advaith1** [comment]
No, this is intended since the source is for spark beta, and the beta site has a different page structure. You can check out the beta site at https://beta.discordspark.com for now, it will be moved to the apex domain when spark 0.1 fully releases.
