### ISSUE TITLE
Help command doesn't work if you can use more than 25 commands

### ISSUE THREAD

**Issue by advaith1** [TobiasFeld22/Spark#55]
The help command doesn't respond if you can use over 25 commands and it has the embed links permission.

**Comment by Sanil14** [comment]
That is because the embed cannot have more than 25 embed fields in one message. I will implement pagination to the command soon. 

Thanks for spotting the issue.

**Comment by TobiasFeld22** [comment]
Still needs some testing, @advaith1 could you confirm?

**Comment by advaith1** [comment]
Now it sends the embed, but only lists 25 commands and the footer says you can use 25 commands. Would it be possible to move the remaining commands into a second embed, or as Sanil said add pagination? Or it might be a better idea to always send the plaintext version when there are over 25.

**Comment by TobiasFeld22** [comment]
Pretty sure pagination works, try `<prefix>help 2`
unless you have exactly 25 commands

**Comment by advaith1** [comment]
Doesn't work, there are more commands but it only shows the same first 25 (if I use a modified version that forces the non-embed view it shows all of them)

**Comment by TobiasFeld22** [comment]
I will look in it tomorrow
