### ISSUE TITLE
[0.0.6] Default `help` command to display command description and possible args

### ISSUE THREAD

**Issue by zocoi** [TobiasFeld22/Spark#57]
Each command currently has a description, I'd love to add args schema and an extra help text which will be displayed when help <command> is called

The point is not to build a separate `help.js`

**Comment by TobiasFeld22** [comment]
@zocoi You can copy the current code for help.js and overwrite the current command with your custom help command. On our release schedule we do have a complete and well thought out argumentation system planned, which will be tied into the help command. This will be planned for version 0.2.0. Until then i suggest making the changes yourself. 
[V0.2 project board](https://github.com/orgs/Sparkbots/projects/4)
Please ask questions like this in our discord server next time.
[![Discord](https://discordapp.com/api/guilds/248505281741455360/embed.png)](https://discord.gg/TezD2Zg)
